spring:
  application:
    name: itoken-eureka


server:
  port: 8761

eureka:
  instance:
    hostname: http://123.207.49.252
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://123.207.49.252:8761/eureka/,http://${eureka.instance.hostname}:8861/eureka/,http://${eureka.instance.hostname}:8961/eureka/

