spring:
  application:
    name: itoken-web-admin
  boot:
    admin:
      client:
        url: http://123.207.49.252:8084
  zipkin:
    base-url: http://123.207.49.252:9411

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8601

feign:
  hystrix:
    enable: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://123.207.49.252:8761/eureka/,http://123.207.49.252:8861/eureka/,http://123.207.49.252:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info