spring:
  application:
    name: itoken-service-redis
  boot:
    admin:
      client:
        url: http://123.207.49.252:8084
  zipkin:
    base-url: http://123.207.49.252:9411
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 47.107.157.226:26379,47.107.157.226:26380,47.107.157.226:26381

server:
  port: 8502

eureka:
  client:
    serviceUrl:
      defaultZone: http://123.207.49.252:8761/eureka/,http://123.207.49.252:8861/eureka/,http://123.207.49.252:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info