spring:
  application:
    name: itoken-config
  boot:
    admin:
      client:
        url: http://47.107.157.226:8084
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/Itokentest/itoken-config.git
          search-paths: respo

  zipkin:
    base-url: http://47.107.157.226:9411

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.107.157.226:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info